### PR TITLE
New widget ByteLabel

### PR DESCRIPTION
**Pull request by AokiAhishatsu**
I used this in two apps to display byte values binary. Might still need some refinement/testing.

### CODE REVIEW

**Review by slightlynybbled — CHANGES_REQUESTED** [review]
`update()` is an existing widget method that is being overwritten: http://effbot.org/tkinterbook/widget.htm .  I'm not sure if it makes a difference or not, but please re-factor to `_update()` or similar.

**Comment by AokiAhishatsu** [comment]
I updated my widget. Can you resolve this conflict?

**Comment by AokiAhishatsu** [comment]
@slightlynybbled  Would it be easier if I commit & push my changes to a new branch? (Not to my fork)

**Comment by slightlynybbled** [comment]
@AokiAhishatsu What you did was no big deal.  I was listening to a podcast a few days ago regarding integrating flake8 into open source projects, so when you started issuing pull requests, I decided that it would be a good idea for this repo.  As a result, a lot of files changed, but not very much.  The bounce from 'auto-mergeable' yesterday to 'manual merge required' last night as a result of me touching so many files.

Just be sure to sync your repository with the primary just before doing the pull request to minimize the differences.  I don't expect that this repository will see a lot of activity, so that likely won't be difficult.  You should get nearly immediate feedback from TravisCI when flake8 doesn't pass.  Other than that, thank you for the contributions!  I created an issue to document your new feature as well so that it doesn't get dropped.  The provided example helps.

**Pull request merged**
